require conf/distro/poky.conf

DISTRO = "training"
DISTRO_NAME = "Example distribution for the training"
DISTRO_VERSION = "1.0"
MAINTAINER = "admin@example.com"

# Select systemd as the sole init manager for this distribution
INIT_MANAGER = "systemd"
#DISTRO_FEATURES:append = " systemd"
#VIRTUAL-RUNTIME_init_manager = "systemd"
#DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit" 
#VIRTUAL-RUNTIME_initscripts = ""

